# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ffd6af29af5158a72d4324699ca4450c3055a43af9527e42a1055c5508b74c2d99f0f19bb906f46709d7face6bdaa9aa78c9e84efd3706b4a9ad8f8adef671a

test:
  secret_key_base: 66da4bf18a9baac97be9db0ecb96486fbd3e899a40efc3961fc735496c618f2a1d73cceb8ba83343706d3b21192980e8437f926694cb6251aa14adf740326edb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
